q1:
	gcc q1-server.c -o q1-server
	gcc q1-client.c -o q1-client

q2:
	gcc q2-server.c -o q2-server
	gcc q2-client.c -o q2-client

clean-q1:
	rm q1-client
	rm q1-server

clean-q2:
	rm q2-client
	rm q2-server
