echo "TCP packets sent from n0 to n2"
grep " 0 2 tcp " tcp-udp.tr | grep -c "r"
echo "TCP packets received from n2 to n3"
grep " 2 3 tcp " tcp-udp.tr | grep -c "r"
echo "TCP packets dropped from n2 to n3"
grep " 2 3 tcp " tcp-udp.tr | grep -c "d"
echo "UDP packets sent from n1 to n2"
grep " 1 2 cbr " tcp-udp.tr | grep -c "r"
echo "UDP packets received from n2 to n3"
grep " 2 3 cbr " tcp-udp.tr | grep -c "r"
echo "UDP packets dropped from n2 to n3"
grep " 2 3 cbr " tcp-udp.tr | grep -c "d"
